### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [kvibber/andre-norton_the-defiant-agents#1]
Commit History:

- [x] In the second commit, splitting the files and running typogrify need to be in separate commits.

dedication.xhtml:

- [x] The dedication needs to be in sentence case. You can make the names appear uppercase by using unsemanticated `<b>` elements and CSS ([SEMOS 4.1.2.3](https://standardebooks.org/manual/1.7.0/single-page#4.1.2.3)).

content.opf:

- [x] Remove "Apaches and Mongols" in the short description ([SEMOS 9.6.1.2](https://standardebooks.org/manual/1.7.0/9-metadata#9.6.1.2)).

cover.source.jpg:

- [x] When you rerun `se build-images .` again, commit the changes.

**Comment by kvibber** [comment]
Whew! OK, I got the rebase done. In my day job we never rewrite the git history, so this is the first time I've actually used it!

**Comment by kvibber** [comment]
And there's the updated cover.source
